### ISSUE TITLE
Incorrect presentation of unquoted registry data in "startup_items" table

### ISSUE THREAD

**Issue by 1ihor1** [osquery/osquery#6402]
# Bug report

### What operating system and version are you using?

 version = 10.0.17763
   build = 17763
platform = windows
### What version of osquery are you using?

version = 4.3.0 (and older)
### What steps did you take to reproduce the issue?
osqueryi  "SELECT * from startup_items"
### What did you expect to see?
A list of startup items with correct data in "path" & "args" columns 
### What did you see instead?
For some items "path" & "args" columns filled in incorrectly: 2nd part of the path (after 1st space symbol in it) moved to "args" column. The issue seems to be valid for items from Registry, which have a space symbol in Value data and are unquoted.
Example: 
![image](https://user-images.githubusercontent.com/36096154/79680409-94c0b900-820f-11ea-8068-5fd4042d9570.png)

**Comment by mike-myers-tob** [comment]
Confirmed this behavior, on osquery 4.6.0. 

But what's surprising is that this is a valid way to store a program path with arguments, because how would a string like this be reliably interpreted correctly? It's actually a security problem, because a malicious executable at `C:\Program` would be run before the intended `Teams.exe`.

In any case, apparently this is just something that Windows does, and `AutoRuns` doesn't have any trouble with it, so osquery should be fixed too.

**Comment by directionless** [comment]
Confirmed as still present in 4.9, I think see why in the code:

https://github.com/osquery/osquery/blob/d2be385d71f401c85872f00d479df8f499164c5a/osquery/tables/system/windows/startup_items.cpp#L75-L79

So if the string has args, of course it won't exist on the file system, and we fall back to splitting on space.

**Comment by branchnetconsulting** [comment]
Confirmed to still occur with 5.6.0.  It sure would be nice to see this parsed cleanly.

**Comment by directionless** [comment]
> My question is: are these entries relevant or should I ignore these entries (and anything that is not a path) ?
At the moment I left them in, to be consistent with the previous behaviour.


I don't know enough windows to know. Maybe someone else does

**Comment by branchnetconsulting** [comment]
By any chance is `startup_items` trying to enumerate all the registry keys that match the pattern `\SOFTWARE\Microsoft\Windows\CurrentVersion\Run*`
and that this RunNotification key is really just some kind of flag rather than an item to execute?

**Comment by directionless** [comment]
> By any chance is `startup_items` trying to enumerate all the registry keys that match the pattern `\SOFTWARE\Microsoft\Windows\CurrentVersion\Run*` and that this RunNotification key is really just some kind of flag rather than an item to execute?

Let's see!
https://github.com/osquery/osquery/blob/b875bf138755b5007cf93a4bec4554ba82fafa1a/osquery/tables/system/windows/startup_items.cpp#L93

Sure looks like it's enumerating there.

**Comment by branchnetconsulting** [comment]
Sure enough, several of the registry key patterns it is looking for end with a prefix of `\\Run%`

https://github.com/osquery/osquery/blob/b875bf138755b5007cf93a4bec4554ba82fafa1a/osquery/tables/system/windows/startup_items.cpp#L35C1-L46C1

I propose logic be added to this startup_items registry key enumeration process that excludes keys whose names end with ` `\\RunNotification`

I'd offer a PR but I am crazy rusty with C.

**Comment by AndreaMarangoni** [comment]
@branchnetconsulting  would you be able to create an issue with your finding, and then I will take care of creating the PR?
